### PR TITLE
Remove dependencies to itself

### PR DESCRIPTION
**Pull request by blankse**
I have after adding this extension problems with other dependencies. After removing this lines, the dependencies works again.

I think this lines makes no sense.

@peterkeung Can you merge this and create a 1.0.1 Tag?

### CODE REVIEW

**Comment by peterkeung** [comment]
Thanks, and sorry about that. Looks like a bad copy and paste that persisted for all these years

**Comment by blankse** [comment]
Thanks for the fast merge :)

**Comment by blankse** [comment]
@peterkeung Can you update packagist? There is no v1.0.1.

**Comment by peterkeung** [comment]
Should be updated now, with v1.0.2 after removing the explicit version declaration in composer.json

**Pull request merged**
