### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by eliosbrocchi**
Hello, coud you add composer.json in your repository and create it on packagist.org?

Thank you, best regards

### CODE REVIEW

**Comment by peterkeung** [comment]
Thanks @eliosbrocchi!

**Comment by blankse** [comment]
@peterkeung Can you also create a v1.0.0 release tag?

I would like add it as required of a bundle.
dev-master is not stable enough.

**Comment by peterkeung** [comment]
Done!

**Comment by blankse** [comment]
Thank you 👍

**Pull request merged**
